### ISSUE TITLE
selenium timeout error

### ISSUE THREAD

**Issue by sedatcanli** [aau-zid/BigBlueButton-liveStreaming#26] opened 2020-05-19 21:06 UTC
Here is the log of docker.

INFO:root:Starting browser!!
INFO:root:Open BBB and hide elements!!
INFO:root:get_join_url...
Traceback (most recent call last):
  File "stream.py", line 121, in <module>
    bbb_browser()
  File "stream.py", line 67, in bbb_browser
    WebDriverWait(browser, selelnium_timeout).until(element)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

I can see the Live user in the room for a while but after some time, it drops and can not start streaming.

**Comment by mtsonline** [comment] 2020-05-19 21:22
Hi,


did you change the language of BBB or remove english?

Or did you disable listen only option?


The streamer searches for the "listen only" button on login and gets a 
timeout if this button cannot be found.


cheers

Martin

**Comment by sedatcanli** [comment] 2020-05-20 06:53
Hi,
I've installed default settings. No any language change, and no any config changes on login screen.
 Thanks.

**Comment by mtsonline** [comment] 2020-05-20 07:49
are you sure, that you have the correct bbb server, secret and meetingID?

**Comment by sedatcanli** [comment] 2020-05-20 08:29
yes. server is running without any problem and secret and meeting ID are correct. When I start docker, I can see the user 'Live' in the room for a while but it disconnects after a while(15 seconds). Moreover my rtmp server is running with OBS but I can not connect with bbb-livestreaming docker.

**Comment by worgil** [comment] 2020-05-20 08:42
Ayar dosyanı paylaşır mısın yani env varsa env yi

**Comment by sedatcanli** [comment] 2020-05-20 11:07
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://MY_URL/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=MY_SECRET
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=MY_MEETING_ID
      # start meeting (optional):
     # - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_ATTENDEE_PASSWORD=dd
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_MODERATOR_PASSWORD=dd
      # meeting title (optional):
      - BBB_MEETING_TITLE=liveStreaming
      # Media server url:
      - BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/qc0k-stqg-r6tr-8dwq-64su

**Comment by worgil** [comment] 2020-05-20 12:18
aşağıdaki satırların karşılığı boş mu ?

# BigBlueButton Server url:
- BBB_URL=https://MY_URL/bigbluebutton/api
# BigBlueButton secret:
- BBB_SECRET=MY_SECRET
# BigBlueButton meetingID:
- BBB_MEETING_ID=MY_MEETING_ID

**Comment by mikosche** [comment] 2020-05-20 12:21
@worgil please write your question in english

cheers 
Michael

**Comment by worgil** [comment] 2020-05-20 12:23
@mikosche 
I trying to help this person and he is Turkish people. This is best and quick way. Sorry if this way disturbing you.
Kind Regards

**Comment by mikosche** [comment] 2020-05-20 12:35
@worgil thank you for helping
I only think that questions and answers could be interesting for other people too, so i would prefer that we all use english.

 greetings

**Comment by mikosche** [comment] 2020-05-20 12:57
Hi,
 the most likely reason for this problem will be that the "Join Audo Modal" or an other action don't shows up which we want to hide.
There will be a better exception handling in one of the next releases.

cheers and thanks to all for your feedback

**Comment by mtsonline** [comment] 2020-05-20 17:54
could you solve the issue?

**Comment by penguennoktanet** [comment] 2020-05-25 16:51
I had the exact same problem. I got this problem on a server which does not had a graphical output (console only) and not audio setup. I somehow overcome graphical issues but can not overcome pulseaudio connection errors.

I switched to a fedora 30+ (can not recall exact version), and every thing works.

**Comment by mtsonline** [comment] 2020-05-25 16:57
@penguennoktanet thanks for the feedback. on which operating system did you have the problems?
As the video and audio devices are run in the docker container it normally should not matter where you use it. Our servers also are setup with just the console and no userinterface.
maybe we can discover the cause with your help.
cheers

**Comment by penguennoktanet** [comment] 2020-05-25 17:12
> @penguennoktanet thanks for the feedback. on which operating system did you have the problems?

Ubuntu 16.04 VPS server which is rented from webtropia.

> As the video and audio devices are run in the docker container it normally should not matter where you use it. Our servers also are setup with just the console and no userinterface.

When I overcome the X problem (can not recall exact error message but it's something about X start error), then the alsa problem poped up (Alsa said it can not connect to pulseaudio, which is not installed on system).

But the funny thing, (by the way, I have more than 20+ years of system administrator experience), when I can not get it work, I reverted all the changes back to original. But now, system seems to work without the changes that I made.. I could not reproduce the errors again... Strange.. Very very strange.

> maybe we can discover the cause with your help.
> cheers

Update: I can reproduce the audio error. When I entered the meeting before the livestream process, I got pulseaudio error;

```
liveStreaming   | [x11grab @ 0x56288d6036c0] Stream #0: not enough frames to estimate rate; consider increasing probesize
liveStreaming   | Input #0, x11grab, from ':122':
liveStreaming   |   Duration: N/A, start: 1590426819.935128, bitrate: N/A
liveStreaming   |     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 29.97 fps, 1000k tbr, 1000k tbn, 1000k tbc
liveStreaming   | ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
liveStreaming   | 
liveStreaming   | [alsa @ 0x56288d60e140] cannot open audio device pulse (Connection refused)
liveStreaming   | pulse: Input/output error
liveStreaming exited with code 0
```

**Comment by mtsonline** [comment] 2020-05-25 17:19
ok. as said, the necessary applications and system tools are installed in the docker, so it should work on any system with enough cpu power and memory.
Let us know if the problem reoccoures. We tested it on ubuntu 16.04 with no issues and also have it running on 18.04.

Think we can close this ticket as there was no feedback regarding the original issue anymore.

**Closed as completed by mtsonline** 2020-05-25 17:19 UTC
