### ISSUE TITLE
Remove My Stream URL from Chat

### ISSUE THREAD

**Issue by sraja415** [aau-zid/BigBlueButton-liveStreaming#50] opened 2020-07-15 15:20 UTC
When live Streaming it shows in Public Chat as

"Live Streaming to : YouTubeStreamURL/StreamKey"

This is very dangerous as stream Key should be kept a secret as anyone can use it to stream to my Channel. Is there a way to hide this Public Chat Message?

**Comment by mtsonline** [comment] 2020-07-15 16:20
this is a duplicate of
#36

**Closed as completed by mtsonline** 2020-07-15 16:20 UTC
